### ISSUE TITLE
vgg-feature-weights.pth在哪

### ISSUE THREAD

**Issue by fc2635540954** [JudgementH/DeepFaceDrawing#2]
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/VGG/vgg-feature-weights.pth'
vgg-feature-weights.pth在哪

**Comment by JudgementH** [comment]
这个我当时写着玩的，现在都没啥印象了。这个VGG-feature应该就是VGGnet的预训练权重，去VGG那里download一下就行吧。

**Comment by fc2635540954** [comment]
我没有找到对应的VGG预训练模型的权重，但改了部分代码暂时跑通了
又遇到了一个新问题，麻烦请教您一下
运行image_generator_execution.py
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/image_generator/feature.npy'

**Comment by JudgementH** [comment]
这个我回忆了一下，需要先调用add_feature_list方法，把所有edge数据都提取特征，然后save_feature_list，完成后就可以load了。本论文应该还有其他比较好的复现，这个我当时就写了2天，有点不完善

**Comment by fc2635540954** [comment]
谢谢大佬，跑通了。
